cloud-sync:
  enabled: true
  url: "https://github.com/rutwok-labs/SF4-Addons/blob/main/Addons/java/core/api/config/addonmanager.yml"
  interval-minutes: 10
  fallback-to-local-on-empty: true
  fallback-to-local-on-failure: true

addons:
  exoticgarden:
    name: "ExoticGarden"
    enabled: false 
    download: true
    auto-update: false
    version: "2605"
    download-url: "https://github.com/rutwok-labs/SF4-Addons/raw/refs/heads/main/Addons/ExoticGarden/releases/ExoticGarden-2604.jar"
    sha256: ""
    checksum-url: ""
    api-url: ""

  electricspawners:
    name: "ElectricSpawners"
    enabled: false
    download: true
    auto-update: false
    version: "100"
    download-url: "https://github.com/rutwok-labs/SF4-Addons/raw/refs/heads/main/Addons/ElectricSpawners/releases/ElectricSpawners%20%23100.jar"
    sha256: ""
    checksum-url: ""
    api-url: ""

    fluffymachines:
    name: "FluffyMachines"
    enabled: false
    download: true
    auto-update: false
    version: "1.0.0"
    download-url: "https://github.com/rutwok-labs/SF4-Addons/raw/refs/heads/main/Addons/FluffyMachines/releases/FluffyMachines%20v1.0.0.jar"
    sha256: ""
    checksum-url: ""
    api-url: ""
